@entryid=bb1b4def-3bcf-4b2f-9cf4-43a9655f3316

GET {{HostAddress}}/api/todoitems

###


GET {{HostAddress}}/api/todoitems{{entryId}}

###



PUT {{HostAddress}}/api/todoitems/{{entryid}}
Content-Type: application/json

{
  "id": "bb1b4def-3bcf-4b2f-9cf4-43a9655f3316",
  "description": "test",
  "isCompleted": true

}

###

POST {{HostAddress}}/api/todoitems
Content-Type: application/json

{
  "description": "test",
  "isCompleted": true
}

###

DELETE {{HostAddress}}/api/todoitems/{{entryid}}

###
